set number
set nocompatible
set ambiwidth=double
set encoding=utf8
set fileencodings=utf-8,iso-2022-jp,cp932,eucjp-ms
set noswapfile
set nobackup
set noundofile
set viminfo=
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
set clipboard=unnamedplus,autoselect
set laststatus=2
set statusline=%-(%f%m%h%q%r%w%)%=%{&ff}\|%{&fenc}\ %y%l,%c\ %0P

" beep
set visualbell
colorscheme peachpuff

"Rainbow Parentheses Improved
let g:rainbow_active=1

set list
set listchars=tab:^\ ,trail:~

autocmd Filetype python set tabstop=4
autocmd Filetype python set shiftwidth=4
autocmd Filetype javascript set tabstop=4
autocmd Filetype javascript set shiftwidth=4

syntax on
filetype plugin indent on
let g:autoflake_remove_all_unused_imports=1
autocmd FileType python map <buffer> <F9> :call Autoflake()<CR>
let g:vim_isort_python_version = 'python2'
autocmd FileType python map <buffer> <F10> :Isort <CR>
autocmd FileType python map <buffer> <F11> :call Autopep8() <CR>
autocmd FileType python map <buffer> <F12> :call Flake8() <CR>
au BufNewFile,BufRead *.hql set filetype=hive expandtab
au BufNewFile,BufRead *.q set filetype=hive expandtab
au BufReadPost,BufNewFile *.tsv :setl noexpandtab

if has('win32')
  source $VIMRUNTIME/mswin.vim
endif
